name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: actions_runner_dev
    steps:
    - uses: actions/checkout@v3
    - name: List the Docker image
      run: docker images
