apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dos-box-runner
  namespace: actions-runner-system-2
spec:
  replicas: 0
  template:
    spec:
      image: summerwind/actions-runner-dind
      env:
        - name: DOCKER_HOST
          value: "tcp://dindsvc:2375"
      dockerdWithinRunnerContainer: true    
      repository: OrgbyRaj/demo-repository
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: "Exists"
        effect: NoSchedule      